logger:
  file: /open5gs/install/var/log/open5gs/bsf.log

global:
  max:
    ue: 1024

bsf:
  sbi:
    server:
      - address: bsf.open5gs.org
        port: 80
    client:
      nrf:
        - uri: http://nrf.open5gs.org:80
